// cli/internal/graph/extract/tsjs/testdata/vue/src/pages/Home.vue
<script setup lang="ts">
import Card from '@app/components/Card.vue';
import EmptyState from '@app/components/EmptyState.vue';
import { useCart, fetchCart } from '@app/composables/useCart';

const cart = useCart();

function reload() {
  fetchCart();
}
</script>

<template>
  <main>
    <Card v-for="item in cart.items" :key="item.id" :item="item" />
    <empty-state v-if="!cart.items.length" @retry="reload" />
  </main>
</template>

// cli/internal/graph/extract/tsjs/testdata/react/src/pages/Home.tsx
import { useEffect } from 'react';
import { Card } from '@app/components/Card';
import { useCart } from '@app/hooks/useCart';

export default function Home() {
  const { items, load } = useCart();
  useEffect(() => {
    load();
  }, [load]);
  return (
    <main>
      {items.map((item) => (
        <Card key={item} title={item} />
      ))}
    </main>
  );
}
